export const C = {
  accent:      '#6441E0',
  accentHover: '#4E3CD6',
  accentLight: '#F8F5FC',
  accentSoft:  '#AB9DF5',
  textGray:    '#798294',
  black:       '#0A0A0A',
  white:       '#FFFFFF',
  border:      '#E8E8ED',
  borderLight: '#F0F0F5',
  green:       '#16A34A',
  greenBg:     '#F0FDF4',
  red:         '#DC2626',
  redBg:       '#FEF2F2',
  orange:      '#D97706',
  orangeBg:    '#FFFBEB',
  purple:      '#7C3AED',
  purpleBg:    '#F5F3FF',
} as const
