import { pgTable, text, timestamp, uuid, integer, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

/**
 * Internal billing (no external payment processor yet — structured so Stripe
 * can be attached later: subscription rows carry a nullable externalRef).
 */
export const subscriptionsTable = pgTable("subscriptions", {
  ownerId: text("owner_id").primaryKey(),
  plan: text("plan").notNull().default("free"), // free | starter | professional | enterprise
  status: text("status").notNull().default("active"), // active | past_due | cancelled
  renewsAt: timestamp("renews_at", { withTimezone: true }),
  externalRef: text("external_ref"), // future Stripe subscription id
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

/** Invoices generated by plan changes/renewals. Amounts in cents. */
export const invoicesTable = pgTable("invoices", {
  id: uuid("id").primaryKey().defaultRandom(),
  ownerId: text("owner_id").notNull(),
  number: text("number").notNull(),
  description: text("description").notNull(),
  amountCents: integer("amount_cents").notNull(),
  currency: text("currency").notNull().default("usd"),
  status: text("status").notNull().default("paid"), // paid | due | void
  issuedAt: timestamp("issued_at", { withTimezone: true }).notNull().defaultNow(),
});

/** Metered usage events (ai_tokens, documents, storage_bytes, agent_runs, tts_seconds, api_requests). */
export const usageEventsTable = pgTable("usage_events", {
  id: uuid("id").primaryKey().defaultRandom(),
  ownerId: text("owner_id").notNull(),
  metric: text("metric").notNull(),
  quantity: integer("quantity").notNull().default(1),
  meta: jsonb("meta").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/** Billing profile (company info, billing email, tax id). */
export const billingProfilesTable = pgTable("billing_profiles", {
  ownerId: text("owner_id").primaryKey(),
  companyName: text("company_name"),
  billingEmail: text("billing_email"),
  taxId: text("tax_id"),
  address: text("address"),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const insertInvoiceSchema = createInsertSchema(invoicesTable).omit({ id: true, issuedAt: true });
export type Subscription = typeof subscriptionsTable.$inferSelect;
export type Invoice = typeof invoicesTable.$inferSelect;
export type UsageEvent = typeof usageEventsTable.$inferSelect;
export type BillingProfile = typeof billingProfilesTable.$inferSelect;
